language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

script:
  - find . -type f -name *.php | xargs -n1 php -l
  - composer install
  - ./vendor/bin/phpunit -v --coverage-text

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      php: 5.3

